workflows:
  android-app:
    name: Android App
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: 18.15.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/android @capacitor/cli
      - name: Build web app
        script: |
          npm run build
      - name: Initialize Capacitor
        script: |
          npx cap init AstroClock com.astroclock.app --web-dir=dist || true
      - name: Add Android platform
        script: |
          npx cap add android || true
      - name: Sync web files to Android
        script: |
          npx cap sync android
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
