workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.15.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/android @capacitor/cli
      - name: Prepare directory structure
        script: |
          mkdir -p src/js src/css dist/src/js dist/src/css
          # Create minimal app.js if it doesn't exist
          if [ ! -f src/js/app.js ]; then
            echo "// Basic app initialization
            document.addEventListener('DOMContentLoaded', function() {
              console.log('AstroClock App initialized');
            });" > src/js/app.js
          fi
          # Create minimal styles.css if it doesn't exist
          if [ ! -f src/css/styles.css ]; then
            echo "body { font-family: 'Inter', sans-serif; }" > src/css/styles.css
          fi
          # Copy files to dist directory
          cp -r src dist/
          cp index.html dist/ || echo "<!DOCTYPE html>
          <html lang='fr'>
          <head>
            <meta charset='UTF-8'>
            <title>AstroClock</title>
            <link rel='stylesheet' href='./src/css/styles.css'>
          </head>
          <body>
            <h1>AstroClock</h1>
            <script type='module' src='./src/js/app.js'></script>
          </body>
          </html>" > dist/index.html
      - name: Build web app
        script: |
          npm run build || echo "Build skipped, using prepared files"
      - name: Initialize Capacitor
        script: |
          npx cap init AstroClock com.astroclock.app --web-dir=dist || true
      - name: Add Android platform
        script: |
          npx cap add android || true
      - name: Sync web files to Android
        script: |
          npx cap sync android
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
