workflows:
  android-app:
    name: Android App
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 18.15.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/core @capacitor/android @capacitor/cli
      - name: Prepare directory structure
        script: |
          mkdir -p src/js src/css dist/src/js dist/src/css
          # Create additional JS files if they don't exist
          if [ ! -f src/js/planets.js ]; then
            touch src/js/planets.js
          fi
          if [ ! -f src/js/ephemerides.js ]; then
            touch src/js/ephemerides.js
          fi
          if [ ! -f src/js/stars.js ]; then
            touch src/js/stars.js
          fi
          if [ ! -f src/js/daily-aspects.js ]; then
            touch src/js/daily-aspects.js
          fi
          # Copy files to dist directory
          cp -r src dist/
          cp index.html dist/ || echo "<!DOCTYPE html>
          <html lang='fr'>
          <head>
            <meta charset='UTF-8'>
            <title>AstroClock</title>
            <link rel='stylesheet' href='./src/css/styles.css'>
          </head>
          <body>
            <h1>AstroClock</h1>
            <script src='./src/js/planets.js'></script>
            <script src='./src/js/ephemerides.js'></script>
            <script src='./src/js/stars.js'></script>
            <script src='./src/js/daily-aspects.js'></script>
            <script src='./src/js/app.js'></script>
          </body>
          </html>" > dist/index.html
      - name: Build web app
        script: |
          npm run build || echo "Build skipped, using prepared files"
      - name: Initialize Capacitor
        script: |
          npx cap init AstroClock com.astroclock.app --web-dir=dist || true
      - name: Add Android platform
        script: |
          npx cap add android || true
      - name: Sync web files to Android
        script: |
          npx cap sync android
      - name: Build Android app
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
